### ISSUE TITLE
false positive D004 Found literal carriage return

### ISSUE THREAD

**Issue by danieltuzes** [PyCQA/doc8#78]
I get false positive
> D004 Found literal carriage return
at every line on Windows. It has been reported here first:
https://bugs.launchpad.net/doc8/+bug/1756704

**Comment by adam-grant-hendry** [comment]
Same here. Unfortunately, adding this to `pyproject.toml`:

```toml
[tool.doc8]
ignore = [ "D004" ]
max_line_length = 90
```

as suggested in #92 doesn't seem to ignore the warning for me in VSCode.

#### System Information
**OS:** Windows 10
**Editor:** VSCode `1.71.2`
**Python:** `3.8`
**doc8:** `0.11.2`
